### ISSUE TITLE
Improved exception/error handling in commands

### ISSUE THREAD

**Issue by classabbyamp** [classabbyamp/discord-qrm2#146]
## `resp.status != 200`

raise custom `ConnectionError`

- [x] ae7q call
- [x] greyline
- [x] hamstudy
- [x] condx
- [x] wttr fc
- [x] wttr now
- [ ] qrz (x6)

## Others

- [x] `ValueError` in grid cmd
- [ ] `Exception` in ungrid cmd (x2)
- [ ] ~~`KeyError` in cww 
    change to `ValueError`~~
- [x] `commands.ExtensionError` in extctl/*

**Comment by 0x5c** [comment]
Ready to close in PR.

Moving remaining work to #181 and #182
