### ISSUE TITLE
Command error handling

### ISSUE THREAD

**Issue by 0x5c** [classabbyamp/discord-qrm2#22]
as described in [the docs](https://discordpy.readthedocs.io/en/latest/ext/commands/commands.html#error-handling)

**Comment by classabbyamp** [comment]
Global Errors:

- [ ] default (any CommandError) -> react with :x:
- [ ] UserInputError (MissingRequiredArgument, ArgumentParsingError, BadArgument, BadUnionArgument, TooManyArguments) -> respond with a message saying what went wrong (arg needed etc)

Errors for specific commands:

- echo:
    - [ ] add check for same server/from DM. maybe make it DM only?
    - [ ] could do CheckFailure/PrivateMessageOnly


???

**Comment by 0x5c** [comment]
### echo
Since it is owner-restricted, it does not require the error-handling of other commands
#### same-server and such
It would be more logical to build a converter that works for all channels the bot sees

The bottom line: Echo requires it's own set of things

### Normal commands
We should handle different kind of errors differently:
- `ConversionError`: I guess same as `CommandInvokeError`?
- `UserInputError`: show the command's help.
- `CommandNotFound`: just catch it and do nothing (log if applicable?).
- `CheckFailure`: ❌ or something? Check failure (or child class) is raised by a check upon failure. We don't implement that currently, and don't use default checks (for now). Some types of checks are more worth logging than others.
- `DisabledCommand`: I don't think we have any of these, but if we did, catching and doing nothing would probably be best.
- `CommandInvokeError`: In-case of a command raising an exception. Pass the original exception and context to `error_embed_factory()`, re-raise or log.
- `CommandOnCooldown`: Do we use cooldowns?

**Comment by classabbyamp** [comment]
> NotFound

we talked about doing :x: to match CheckFailure so people can't find the admin commands by dictionary

> Disabled

right we don't have any, but I say do the :x: to match CheckFailure/NotFound

> Invoke

agree

> Cooldown

no, but could put it in there as :x: for future compatibility

**Comment by 0x5c** [comment]
I would really do Cooldown as a different feedback, since the command does exist

Also, we need to ensure that emojis are added with `common.add_react()`

**Comment by 0x5c** [comment]
Note: function to override is `on_command_error()`

**Comment by 0x5c** [comment]
- `UserInputError`: show the command's help.
- `CommandNotFound`: react "❓"
- `CheckFailure`: *accordingly*; our is_owner check should react "⛔️"
- `DisabledCommand`: react "‼️" 
- `CommandInvokeError`: Pass the original exception and context to `error_embed_factory()`, re-raise or log. +react "⚠️" 
- `ConversionError`: Same as `CommandInvokeError`
- `CommandOnCooldown`: Impl cooldowns separately, #144. react "🛑⏳"
