### ISSUE TITLE
Normalise aiohttp requests

### ISSUE THREAD

**Issue by classabbyamp** [classabbyamp/discord-qrm2#49]
instead of opening a session, use `aiohttp.request('GET', url)`

**Comment by classabbyamp** [comment]
```
exts/image.py:61
exts/weather.py:34
exts/weather.py:84
exts/weather.py:118
exts/study.py:57
exts/ae7q.py:41
```
these are the ones that should be changed I think

**Comment by 0x5c** [comment]
According to [aiohttp's documentation](https://aiohttp.readthedocs.io/en/stable/client_advanced.html#client-session),
> The session contains a cookie storage and connection pool, thus cookies and connections are shared between HTTP requests sent by the same session.

Since the sessions aren't site-specific, should the bot have a single session, shared to all extensions?

**Comment by classabbyamp** [comment]
hm that could be good
